"""change unique constraints in tables

Revision ID: 2fe894138c8a
Revises: 6ca69bd8aefa
Create Date: 2023-05-18 08:52:59.214640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe894138c8a'
down_revision = '6ca69bd8aefa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_username_email_id', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('unique_user_username_email_id', 'users', ['username', 'email', 'id'])
    # ### end Alembic commands ###
