"""change unique constraint in table PhotoFilter

Revision ID: 6ca69bd8aefa
Revises: 534cb6694019
Create Date: 2023-05-18 07:32:44.075179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca69bd8aefa'
down_revision = '534cb6694019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_filters_name', table_name='photo_filters')
    op.create_index(op.f('ix_photo_filters_name'), 'photo_filters', ['name'], unique=False)
    op.create_unique_constraint('unique_name', 'photo_filters', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name', 'photo_filters', type_='unique')
    op.drop_index(op.f('ix_photo_filters_name'), table_name='photo_filters')
    op.create_index('ix_photo_filters_name', 'photo_filters', ['name'], unique=False)
    # ### end Alembic commands ###
