"""add table photo_transformations

Revision ID: 7fe7b73929fd
Revises: e91870495617
Create Date: 2023-05-15 15:16:23.971506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe7b73929fd'
down_revision = 'e91870495617'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_transformations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('transformed_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('photos', sa.Column('cloud_public_id', sa.String(length=255), nullable=False))
    op.alter_column('photos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('photos', 'url_photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'url_photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('photos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('photos', 'cloud_public_id')
    op.drop_table('photo_transformations')
    # ### end Alembic commands ###
