"""add created_at, updated_at in Photo

Revision ID: b25c92a26661
Revises: 2fe894138c8a
Create Date: 2023-05-20 12:43:27.584941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25c92a26661'
down_revision = '2fe894138c8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('photos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'updated_at')
    op.drop_column('photos', 'created_at')
    # ### end Alembic commands ###
