#--> email 
EMAIL_MAX__LEN = 50
EMAIL_MIN_LEN = 5

#--> username
USERNAME_MIN_LEN = 5
USERNAME_MAX_LEN = 30

#--> password
PASSWORD_MIN_LEN = 6
PASSWORD_MAX_LEN = 10

#--> first_name
FIRST_NAME_MIN_LEN = 3
FIRST_NAME_MAX_LEN = 20

#--> comment
COMMENT_MIN_LEN = 1

#--> tag
TAG_MIN_LEN = 1

#-->schemas/photos.response_model
MAX_LENGTH_PHOTO_DESCRIPTION = 255

#-->schemas/photos_filters
MIN_LEN_PHOTO_FILTER_NAME = 3
MAX_LEN_PHOTO_FILTER_NAME = 128
MAX_LEN_PHOTO_FILTER_DESC = 128

