BASE_DESCRIPTION_LEN = 255

#--> email
EMAIL_MAX__LEN = 50
EMAIL_MIN_LEN = 5

#--> username
USERNAME_MIN_LEN = 5
USERNAME_MAX_LEN = 30

#--> password
PASSWORD_MIN_LEN = 6
PASSWORD_MAX_LEN = 10

#--> first_name
FIRST_NAME_MIN_LEN = 3
FIRST_NAME_MAX_LEN = 20

#--> comment
COMMENT_MIN_LEN = 1

#--> photo transformer name
TRANSFORMER_NAME_MIN_LEN = 1
TRANSFORMER_NAME_MAX_LEN = 128


